version: '3.7'
services:
  apache:
    container_name: iim_apache
    hostname: iim_apache
    build: ./containers/apache
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php:php'
    volumes:
      - './src:/usr/local/apache2/htdocs'
  php:
    container_name: iim_php
    hostname: iim_php
    build: ./containers/php
    links:
      - 'mysql:mysql'
    volumes:
      - './src:/var/www/html'
  mysql:
    container_name: iim_mysql
    hostname: iim_mysql
    build: ./containers/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root